-- AlterTable
ALTER TABLE "Project" ALTER COLUMN "contentImages" SET DEFAULT ARRAY[]::VARCHAR(255)[];

-- AlterTable
ALTER TABLE "Repo" ADD COLUMN     "archived" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "forked" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "forkedGitHubNodeID" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "forkedGitHubOwnerID" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "forkedGitHubRepoID" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "forkerRepoFullName" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "forks" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "openIssues" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "repoCreatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "repoPushedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
