version: "3.8"  # optional since v1.27.0
services:
  postgres:
    image: postgres:14-alpine
    container_name: hastidb
    ports:
      - 5432:5432
    networks:
      - hastinet
    volumes:
      - ~/postgres/data:/var/lib/postgresql/data
    env_file:
      - .env

  hastibackend:
    container_name: hastibackend
    restart: always
    depends_on:
      - postgres
    image: jameswrc/hastibackend
    # env_file Will be overriden by the environment variables in elasticbeanstalk configuration.
    env_file:
      - .env
    ports:
      - 3117:3000
    networks:
      - traefik_default_network
      - hastinet
    labels:
      - traefik.enable=true
      - traefik.http.routers.hastibackend.rule=Host(`${SUBDOMAIN}.${ZONE}`)
      - traefik.http.routers.hastibackend.tls=true
      - traefik.http.routers.hastibackend.tls.certresolver=myresolver
      - traefik.http.routers.hastibackend.entrypoints=websecure
      - traefik.http.services.hastibackend.loadbalancer.server.port=3117
      - traefik.docker.network=traefik_default_network

networks:
  traefik_default_network:
    driver: bridge
  hastinet: