branch-defaults:
  default:
    environment: Hasti-backend-env-2
    group_suffix: null
global:
  application_name: hasti-backend
  branch: null
  default_ec2_keyname: hasti-backend-sshkey
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
