# Use postgres/example user/password credentials
version: '3.9'

services:
  typesense:
    image: typesense/typesense:0.25.2
    restart: unless-stopped
    ports:
      - "8108:8108"
    volumes:
      - /mnt/dbstore/typesense/data:/data
    env_file:
      - .env
    command: '--data-dir /data --api-key=${TYPESENSE_KEY} --enable-cors'